---
title: "MIMICSp Initial MCMC"
author: "Aaron Price"
date: "2024-10-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Env.
```{r}
library(tidyverse)
library(rootSolve)
library(boot)
library(ggplot2)
```

# Model Execution Function
```{r}
# "Jitter step" re-run function if solve unsuccesful (eg. MICk = 0 crash)
stode_jitter <- function(stode_y = Ty, stode_time = 1e6, stode_fun = RXEQ, stode_parms = params, stode_pos = TRUE, run_i = 0) {
  success <- FALSE
  while (!success) {
    run_i <- run_i + 1
    test  <- quiet(stode(y = stode_y, 
                         time = stode_time, 
                         fun = stode_fun, 
                         parms = stode_parms, 
                         positive = stode_pos)) #Suppress: "diagonal element is zero"
    
    tbl <- as.numeric(test[[1]])
    # Repeat stode ftn if the r or K microbial pools crash below 1e-10
    success <- tbl[3] > 1e-10 & tbl[4] > 1e-10
    
    if(!success) {
      #Add 1% on to Ty$mic2 if no success
      stode_y['MIC_2'] = stode_y['MIC_2'] * 1.01
    }
    
    if(run_i > 5) {
      success <- TRUE
    }
  }
  
  return(c(test,run_i))
}
```

# Default parameters
```{r}
# Default parameters (may not be neccessary w/ MCMC setup)
Vslope  <- rep(0.063, 7) # Modified for MICa
Vint    <- rep(5.47, 7) # Modified for MICa
aV      <- rep(0.000008, 7)  # Modified for MICa
Kslope  <- c(0.025, 0.035, 0.025, 0.025, 0.035, 0.025, 0.025) # Modified for MICa
Kint    <- rep(3.19, 7) # Modified for MICa
aK      <- rep(10, 7) # Modified for MICa
vMOD    <- c(10, 2, 10, 3, 3, 2, 2) # Modified for MICa
kMOD    <- c(8, 2, 4, 2, 4, 6, 2) # Modified for MICa
KO      <- c(6, 6, 6) # Modified for MICa
CUE     <- c(0.55, 0.25, 0.75, 0.35, 0.2) # Modified for MICa
tau_r   <- c(0.00052, 0.3)
tau_K   <- c(0.00024, 0.1)
tau_a   <- c(0.00024, 0.1) # Added for MICa
Tau_MOD <- c(100, 0.8, 1.2, 2) # Modified for MICa
Tau_MULT <- 1
fPHYS_r <- c(0.3, 1.3)
fPHYS_K <- c(0.2, 0.8)
fPHYS_a <- c(0.2, 0.8) # Added for MICa
fCHEM_r <- c(0.1, -3, 1)
fCHEM_K <- c(0.3, -3, 1)
fCHEM_a <- c(0.3, -3, 1) # Added for MICa
fSOM_p  <- c(0.000015, -1.5)
PHYS_scalar <- c(2, -2, NA, NA, NA, NA)
FI      <- c(0.05, 0.05)
fmet_p <- c(1.2, 0.85, 0.013)
depth <- 30 ###
h2y        <- 24*365
MICROtoECO <- depth * 1e4 * 1e-3  # mgC/cm3 to g/m2

#Set default multipliers
Tau_MULT = 1
desorb_MULT = 1
fPHYS_MULT = 1
```

# Function to run MIMICS-p
```{r}
# MIMICS single point function
MIMICS1 <- function(df, params){
  
  ### Setup a var to collect run notes
  note <- ""
  
  ### Bring in lig:N forcing data
  lig_N <- df$lig_N
  
  # Set fMET equation
  # Option A: Defualt fMET equation using lig:N values
  fMET <- fmet_p[1] * (fmet_p[2] - fmet_p[3] * lig_N) 
  # Option B: LTER "SHORTCUT" fMET value (average from LiDET)
  #fMET <- 0.3846423
  
  #ANPP       <- df$pGPP ###Bring in forcing ANPP value
  #ANPP <-  (ANPP+400)/2 # Modify as necessary to approximate ANPP
  # e.g. ANPP ~ GPP from MSAVI +400, then divided by 2 

  ANPP <- df$ANPP
  
  if(ANPP < 1){
    ANPP <- 1.19999
    print("Fixing ANPP < 1")
  } #prevent negative ANPP

    fCLAY      <- df$CLAY/100 # Clay % to decimal

  if(fCLAY < 0.02) {
    fCLAY <- 0.02
    print("Low clay value set to 2%")
  } # Prevent clay < 3%
  
  ### Bring in TSOI value
  TSOI       <- df$TSOI
  
  EST_LIT <- (ANPP / (365*24)) * 1e3 / 1e4 # Calc litter input rate
  
  # Caclulate parameters
  Vmax     <- exp(TSOI * Vslope + Vint) * aV 
  Km       <- exp(TSOI * Kslope + Kint) * aK
  
  Tau_MOD1 <- sqrt(ANPP/Tau_MOD[1])         
  Tau_MOD2 <- Tau_MOD[4]                        
  Tau_MOD1[Tau_MOD1 < Tau_MOD[2]] <- Tau_MOD[2]
  Tau_MOD1[Tau_MOD1 > Tau_MOD[3]] <- Tau_MOD[3] 
  tau <- c(tau_r[1]*exp(tau_r[2]*fMET), 
           tau_K[1]*exp(tau_K[2]*fMET),
           tau_a[1]*exp(tau_a[2]*fMET))   
  tau <- tau * Tau_MOD1 * Tau_MOD2 * Tau_MULT 
  
  fPHYS    <- c(fPHYS_r[1] * exp(fPHYS_r[2]*fCLAY), 
                fPHYS_K[1] * exp(fPHYS_K[2]*fCLAY),
                fPHYS_a[1] * exp(fPHYS_a[2]*fCLAY)) 	            
  fCHEM    <- c(fCHEM_r[1] * exp(fCHEM_r[2]*fMET) * fCHEM_r[3], 
                fCHEM_K[1] * exp(fCHEM_K[2]*fMET) * fCHEM_K[3],
                fCHEM_a[1] * exp(fCHEM_a[2]*fMET) * fCHEM_a[3]) 	
  fAVAI    <- 1 - (fPHYS + fCHEM)
  desorb   <- fSOM_p[1] * exp(fSOM_p[2]*(fCLAY))                  
  
  desorb <- desorb * desorb_MULT
  fPHYS <- fPHYS * fPHYS_MULT
  
  pSCALAR  <- PHYS_scalar[1] * exp(PHYS_scalar[2]*(sqrt(fCLAY)))  #Scalar for texture effects on SOMp
  v_MOD    <- vMOD  
  k_MOD    <- kMOD 
  k_MOD[3] <- k_MOD[3] * pSCALAR    
  k_MOD[6] <- k_MOD[6] * pSCALAR    
  
  VMAX     <- Vmax * v_MOD 
  KM       <- Km / k_MOD

  #initialize pools
  I       <- array(NA, dim=2)             
  I[1]    <- (EST_LIT / depth) * fMET     
  I[2]    <- (EST_LIT / depth) * (1-fMET)
  lit     <- I   
  mic     <- I  
  mic_a   <- 0.001 # Initializing MICa
  som     <- rep(NA, 3)
  som[1]  <- I[1]
  som[2]  <- I[2]
  som[3]  <- I[1] 
  LITmin  <- rep(NA, dim=6)
  MICtrn  <- c(NA,NA,NA,NA,NA,NA,NA,NA,NA) #Updated w/ MIC_A placeholders
  SOMmin  <- rep(NA, dim=3) #Updated w/ MIC_A placeholders
  DEsorb  <- rep(NA, dim=1)
  OXIDAT  <- rep(NA, dim=1)
  
  #Calculate RXEQ pools  
  Tpars <- c( I = I, VMAX = VMAX, KM = KM, CUE = CUE, 
              fPHYS = fPHYS, fCHEM = fCHEM, fAVAI = fAVAI, FI = FI, 
              tau = tau, LITmin = LITmin, SOMmin = SOMmin, MICtrn = MICtrn, 
              desorb = desorb, DEsorb = DEsorb, OXIDAT = OXIDAT, KO = KO)
  Ty    <- c( LIT_1 = lit[1], LIT_2 = lit[2], 
              MIC_1 = mic[1], MIC_2 = mic[2], MIC_A = mic[2],
              SOM_1 = som[1], SOM_2 = som[2], SOM_3 = som[3])
  
  ## Set global parameters to allow pass to stode function
  .GlobalEnv$VMAX <- VMAX
  .GlobalEnv$KM <- KM
  .GlobalEnv$fPHYS <- fPHYS
  .GlobalEnv$fCHEM <- fCHEM
  .GlobalEnv$fAVAI <- fAVAI
  .GlobalEnv$I <- I
  .GlobalEnv$tau <- tau
  .GlobalEnv$LITmin <- LITmin
  .GlobalEnv$SOMmin <- SOMmin
  .GlobalEnv$MICtrn <- MICtrn
  .GlobalEnv$desorb <- desorb
  .GlobalEnv$DEsorb <- DEsorb
  .GlobalEnv$OXIDAT <- OXIDAT
  
  
  # Using jitter
  test  <- stode_jitter(stode_y = Ty, stode_time = 1e6, stode_fun = RXEQ, stode_parms = Tpars, stode_pos = TRUE)
  
  # Not using jitter
  #test  <- stode(y = Ty, time = 1e6, fun = RXEQ, parms = Tpars, positive = TRUE)
  
  
  ### Calc and get MIMICS output 
  MIMLIT    <- (test[[1]][[1]]+test[[1]][[2]])  * depth *1e4 / 1e6 #convert kgC/m2 from mgC/cm3 (0-30 cm) 
  MIMMIC    <- (test[[1]][[3]]+test[[1]][[4]])  * depth *1e4 / 1e6
  MIM_CO    <-  test[[1]][[3]]/test[[1]][[4]]
  MIMSOC    <- sum(test[[1]])  * depth *1e4 / 1e6   
  
  table <- as.numeric(test[[1]])
  
  MIMout <- data.frame(Site = df$Site,
                       fCLAY = fCLAY,
                       TSOI = TSOI,
                       ANPP = ANPP,
                       LIGN = lig_N,
                       EST_LIT = EST_LIT,
                       MIMSOC = MIMSOC,
                       MIMMIC = MIMMIC,
                       MIMLIT = MIMLIT,
                       MIM_CO = MIM_CO,
                       desorb = as.numeric(desorb),
                       SOMpTOv = 1/(as.numeric(desorb)*24*365), #convert from per hr to per yr
                       LITm = table[1] * depth *1e4 / 1e6, #convert kgC/m2 from mgC/cm3 (0-30 cm) 
                       LITs = table[2] * depth *1e4 / 1e6,
                       MICr = table[3] * depth *1e4 / 1e6,
                       MICK = table[4] * depth *1e4 / 1e6,
                       MICa = table[5] * depth *1e4 / 1e6,
                       SOMp = table[6] * depth *1e4 / 1e6,
                       SOMc = table[7] * depth *1e4 / 1e6,
                       SOMa = table[8] * depth *1e4 / 1e6,
                       JITn = test[[2]],
                       DEBUG = note
  )
  #Reset global parameters from last run
  # .GlobalEnv$VMAX <- NA
  # .GlobalEnv$KM <- NA
  # .GlobalEnv$fPHYS <- NA
  # .GlobalEnv$fCHEM <- NA
  # .GlobalEnv$fAVAI <- NA
  # .GlobalEnv$I <- NA
  # .GlobalEnv$tau <- NA
  # .GlobalEnv$LITmin <- NA
  # .GlobalEnv$SOMmin <- NA
  # .GlobalEnv$MICtrn <- NA
  # .GlobalEnv$desorb <- NA
  # .GlobalEnv$DEsorb <- NA
  # .GlobalEnv$OXIDAT <- NA
  
  #remove global variables set for stode ftn
  #rm(I, VMAX, KM, fPHYS, fCHEM, fAVAI, tau, LITmin, SOMmin, MICtrn, desorb, DEsorb, OXIDAT)
  
  return(MIMout)
}
```

# MIMICS-p model function
```{r}
#Model Function
RXEQ <- function(t, y, pars) {
  with (as.list(c(y, pars)),{
    
    #Flows to and from MIC_1
    LITmin[1] = MIC_1 * VMAX[1] * LIT_1 / (KM[1] + MIC_1)   #MIC_1 decomp of MET lit
    LITmin[2] = MIC_1 * VMAX[2] * LIT_2 / (KM[2] + MIC_1)   #MIC_1 decomp of STRUC lit
    MICtrn[1] = MIC_1 * tau[1]  * fPHYS[1]                  #MIC_1 turnover to PHYSICAL SOM 
    MICtrn[2] = MIC_1 * tau[1]  * fCHEM[1]                  #MIC_1 turnover to CHEMICAL SOM  
    MICtrn[3] = MIC_1 * tau[1]  * fAVAI[1]                  #MIC_1 turnover to AVAILABLE SOM  
    SOMmin[1] = MIC_1 * VMAX[3] * SOM_3 / (KM[3] + MIC_1)   #decomp of SOMa by MIC_1
    
    #Flows to and from MIC_2
    LITmin[3] = MIC_2 * VMAX[4] * LIT_1 / (KM[4] + MIC_2)   #decomp of MET litter
    LITmin[4] = MIC_2 * VMAX[5] * LIT_2 / (KM[5] + MIC_2)   #decomp of SRUCTURAL litter
    MICtrn[4] = MIC_2 * tau[2]  * fPHYS[2]                  #MIC_2 turnover to PHYSICAL  SOM 
    MICtrn[5] = MIC_2 * tau[2]  * fCHEM[2]                  #MIC_2 turnover to CHEMICAL  SOM  
    MICtrn[6] = MIC_2 * tau[2]  * fAVAI[2]                  #MIC_2 turnover to AVAILABLE SOM  
    SOMmin[2] = MIC_2 * VMAX[6] * SOM_3 / (KM[6] + MIC_2)   #decomp of SOMa by MIC_2
    
    # Flows to and from MICa
    LITmin[5] = MIC_A * VMAX[7] * LIT_1 / (KM[7] + MIC_A)   #decomp of MET litter
    LITmin[6] = MIC_A * VMAX[7] * LIT_2 / (KM[7] + MIC_A)   #decomp of SRUCTURAL litter   
    MICtrn[7] = MIC_A * tau[3] * fPHYS[3]                   #MIC_A turnover to PHYSCIAL SOM
    MICtrn[8] = MIC_A * tau[3] * fCHEM[3]                   #MIC_A turnober to CHEMICAL SOM
    MICtrn[9] = MIC_A * tau[3] * fAVAI[3]                   #MIC_A turnover to AVAILABLE SOM
    SOMmin[3] = MIC_A * VMAX[7] * SOM_3 / (KM[7] + MIC_A)   #decomp of SOMa by MIC_A         
    
    
    # Protected C pool losses
    DEsorb    = SOM_1 * desorb  #  	#desorbtion of PHYS to AVAIL (function of fCLAY)
    OXIDAT    = ((MIC_1 * VMAX[2] * SOM_2 / (KO[1]*KM[2] + MIC_1)) +
                   (MIC_2 * VMAX[5] * SOM_2 / (KO[2]*KM[5] + MIC_2)) + 
                    (MIC_A * VMAX[7] * SOM_2 / (KO[3]*KM[7] + MIC_A)))  #oxidation of C to A
    
    # ODE System 
    dLIT_1 = I[1]*(1-FI[1]) - LITmin[1] - LITmin[3] 
    dMIC_1 = CUE[1]*(LITmin[1]+ SOMmin[1]) + CUE[2]*(LITmin[2]) - (MICtrn[[1]] + MICtrn[[2]] + MICtrn[[3]])
    dSOM_1 = I[1]*FI[1] + MICtrn[1] + MICtrn[4] + MICtrn[7] - DEsorb 
    dLIT_2 = I[2] * (1-FI[2]) - LITmin[2] - LITmin[4] #- LITmin[6]
    dMIC_2 = CUE[3]*(LITmin[3]+ SOMmin[2]) + CUE[4]*(LITmin[4]) - (MICtrn[[4]] + MICtrn[[5]] + MICtrn[[6]])
    dSOM_2 = I[2]*FI[2] + MICtrn[2] + MICtrn[5] + MICtrn[8] - OXIDAT
    dSOM_3 = MICtrn[3] + MICtrn[6] + DEsorb + OXIDAT - SOMmin[1] - SOMmin[2] - SOMmin[3] + MICtrn[9]
    dMIC_A = (CUE[5] * (SOMmin[3] + LITmin[4] + LITmin[5])) - (MICtrn[[7]]) 
    
    # Return Function 
    list(c(dLIT_1, dLIT_2, dMIC_1, dMIC_2, dMIC_A, dSOM_1, dSOM_2, dSOM_3))
  })
}

quiet <- function(x) { 
  sink(tempfile()) 
  on.exit(sink()) 
  invisible(force(x)) 
} #Remove STODE warning "diagonal element is 0"
```

# Setup parameters for MCMC run
```{r}
# Default parameters 
params <- list()
params$Vslope  <- rep(0.063, 7) # Modified for MICa
params$Vint    <- rep(5.47, 7) # Modified for MICa
params$aV      <- rep(0.000008, 7)  # Modified for MICa
params$Kslope  <- c(0.025, 0.035, 0.025, 0.025, 0.035, 0.025, 0.025) # Modified for MICa
params$Kint    <- rep(3.19, 7) # Modified for MICa
params$aK      <- rep(10, 7) # Modified for MICa
params$vMOD    <- c(10, 2, 10, 3, 3, 2, 2) # Modified for MICa
params$kMOD    <- c(8, 2, 4, 2, 4, 6, 2) # Modified for MICa
params$KO      <- c(6, 6, 6) # Modified for MICa
params$CUE     <- c(0.55, 0.25, 0.75, 0.35, 0.2) # Modified for MICa
params$tau_r   <- c(0.00052, 0.3) 
params$tau_K   <- c(0.00024, 0.1)
params$tau_a   <- c(0.00024, 0.1) # Modified for MICa
params$Tau_MOD <- c(100, 0.8, 1.2, 2)
params$Tau_MULT <- 1
params$fPHYS_r <- c(0.3, 1.3)
params$fPHYS_K <- c(0.2, 0.8)
params$fPHYS_a <- c(0.2, 0.8) # Modified for MICa
params$fCHEM_r <- c(0.1, -3, 1)
params$fCHEM_K <- c(0.3, -3, 1)
params$fCHEM_a <- c(0.3, -3, 1) # Modified for MICa
params$fSOM_p  <- c(0.000015, -1.5)
params$PHYS_scalar <- c(2, -2, NA, NA, NA, NA) 
params$FI      <- c(0.05, 0.05)
params$fmet_p <- c(1, 0.85, 0.013)
params$depth <- 30
params$h2y        <- 24*365
params$MICROtoECO <- depth * 1e4 * 1e-3  # mgC/cm3 to g/m2

#Set default multipliers
params$Tau_MULT = 1
params$desorb_MULT = 1
params$fPHYS_MULT = 1
```

# Run model for test

```{r}
data <- data <- read.csv("TESTOBS.csv", as.is=T)

MIMtest <- data %>% split(1:nrow(data)) %>% map(~ MIMICS1(df=.)) %>% bind_rows()
MIMtest <- MIMtest |>
  select('Site', 'MIMSOC', 'MIMLIT', 'MIMMIC',
         'LITm', 'LITs',
         'MICr', 'MICK', 'MICa',
         'SOMp', 'SOMc', 'SOMa')

MIMtest
```


# MCMC configuration and proposed parameter objects

```{r}
# Set MCMC Configuration
num_iter <- 5000
log_likelihood_prior_current <- -10000000000
accept <- 0


# Initialize chain
num_pars <- 3
jump_params <- c(0.01, 0.01, .01)

# Select parameters for fit
fit_params <- array(NA, dim = c(num_pars, num_iter))
fit_params[1, 1] <- params$Vslope[7]
fit_params[2, 1] <- params$Kslope[6]
fit_params[3, 1] <- params$Kslope[3]


# Distribution of priors
prior_mean <- c(params$Vslope[7] / 2, 
                params$Vslope[6],
                params$Vslope[3])

prior_sd <- c(0.025, 
              0.025, 
              0.025)
```

# Observations
```{r}
obs <- read.csv('testData.csv')

obs <- obs |>
  select(FID, Site, SOC, MICr, sds) |> #SOMp, SOMc, SOMa, MICr, sds) |>
  rename(MICa = MICr) # Assume MICa and MICr should be similar abundance

obs$model_id <- 'observation'

obs_long <- pivot_longer(obs,
  cols = c('MICa', 'SOC', 'MICa'), # 'SOMp', 'SOMc', 'SOMa'),
  names_to = 'variable',
  values_to = 'observed')

obs_long <- obs_long |>
  mutate(sds = case_when(variable == 'MICa' ~ sds,
                         variable == 'SOC' ~ 1))
```

# MCMC execution 
```{r}
for(iter in 2:num_iter){
  # Loop through parameter value
  for(j in 1:num_pars){
    
    # Setting proposed parameter values
    proposed_pars <- fit_params[, iter - 1]
    proposed_pars[j] <- rnorm(1, mean = fit_params[j, iter - 1], sd = jump_params[j])
    
    
    log_prior <- dnorm(proposed_pars[1], mean = prior_mean[1], sd = prior_sd[1], log = TRUE) +
      dnorm(proposed_pars[2], mean = prior_mean[2], sd = prior_sd[2], log = TRUE) +
      dnorm(proposed_pars[3], mean = prior_mean[3], sd = prior_sd[3], log = TRUE) 

    
    params$Vslope[7]  <- proposed_pars[1]
    params$Kslope[7]  <- proposed_pars[2]
    params$tau_a[2] <- proposed_pars[3]
    
    # Run Model w/in MCMC
    data <- data <- read.csv("testData.csv", as.is=T)
 
    MIMrun <- data %>% split(1:nrow(data)) %>% map(~ MIMICS1(df=.)) %>% bind_rows()
    MIMrun <- data %>% cbind(MIMrun %>% select(-Site, -TSOI))
    
    # Combine model data w/ observations
    MIMrun$model_id <- 'fitting'

    MIMrun_long <- MIMrun |>
      select('FID', 'MICa', 'MIMSOC') |>
      rename(SOC = MIMSOC) |> #, 'SOMp', 'SOMc', 'SOMa') |>
      pivot_longer(cols = c('SOC', 'MICa'), #'SOMp', 'SOMc', 'SOMa'),
                  names_to = 'variable',
                  values_to = 'predicted')
    
    combined_output_obs <- MIMrun_long |>
      left_join(obs_long, by = c('FID', 'variable'))
    
    # Likelihood analysis (bayes comparison)
    log_likelihood <- sum(dnorm(x =  combined_output_obs$observed, 
                                mean = combined_output_obs$predicted, 
                                sd = combined_output_obs$sds, log = TRUE))
    
    log_likelihood_prior_proposed <- log_prior + log_likelihood
    
    z <- exp(log_likelihood_prior_proposed - log_likelihood_prior_current)
    
    r <- runif(1, min = 0, max = 1)
    
    if(z >  r){
      fit_params[j, iter] <- proposed_pars[j]
      log_likelihood_prior_current <- log_likelihood_prior_proposed
      accept <- accept + 1
    }else{
      fit_params[j, iter] <- fit_params[j, iter - 1]
      log_likelihood_prior_current <- log_likelihood_prior_current 
    }
  }
}
    
```

# Check model output
```{r}
print('Last Output from MCMC run')
combined_output_obs
```

# Analyze MCMC results 
```{r}
accept / (num_iter * num_pars)
```

```{r}
nburn <- 1
parameter_MCMC <- tibble(iter = nburn:num_iter,
            Vslope_a = fit_params[1, nburn:num_iter],
            Vslope_r = fit_params[2, nburn:num_iter],
            Vslope_k = fit_params[3, nburn:num_iter])%>%
  pivot_longer(-iter, values_to = "value", names_to = "parameter")
```

```{r}
p1 <- ggplot(parameter_MCMC, aes(x = iter, y = value)) +
  geom_line() +
  facet_wrap(~parameter, scales = "free") +
  theme_bw()

p1
```

```{r}
nburn <- 50
parameter_MCMC <- tibble(iter = nburn:num_iter,
            Vslope_a = fit_params[1, nburn:num_iter],
            Vslope_r = fit_params[2, nburn:num_iter],
            Vslope_k = fit_params[3, nburn:num_iter])%>%
  pivot_longer(-iter, values_to = "value", names_to = "parameter")
```

```{r}
p1 <- ggplot(parameter_MCMC, aes(x = iter, y = value)) +
  geom_line() +
  facet_wrap(~parameter, scales = "free") +
  theme_bw()

p1
```

```{r}
p2 <- ggplot(parameter_MCMC, aes(x = value)) +
  geom_histogram() +
  facet_wrap(~parameter, scales = "free") +
  theme_bw()

p2

mean_tab <- parameter_MCMC |>
  group_by(parameter) |>
  summarise(parm_mean = mean(value)) |>
  as.data.frame()

mean_tab

sd_tab <- parameter_MCMC |>
  group_by(parameter) |>
  summarise(parm_sd = sd(value)) |>
  as.data.frame()

sd_tab
```


